#!/usr/bin/env python
import subprocess
import time 

tmp = 10
file = 1
for i in range(0, 110, 10):
    relevant_line = 0
    with open('simulation/config.py', 'r') as f:
        lines = f.readlines()
        for j, line in enumerate(lines):
            if line.startswith('NEW_CUSTOMERS'):
                relevant_line = j
    with open('simulation/config.py', 'w') as f:
        lines[relevant_line] = f'NEW_CUSTOMERS = {i}\n'
        f.writelines(lines)
    time.sleep(1) 
    subprocess.Popen([f'python single.py > outs/out{file}'], shell = True)
    file += 1

